SELECT	day,																				
		month,																		
		year,																																				
		district,
		facility,
		first_name,
		last_name,
		age,
		sex,
		phone,
		position,
		catchment_name,
		catchment_pop,
		trained,
		device_condition,
		chall_connect,
		chall_power,
		device_ichis,
		device_otherapp,
		when_record,
		version,
		device_update,
		ichis_household,
		chr_household,
		ichis_individual,
		chr_individual,
		records_complete,
		age_match,
		sex_match,
		action_plan,
		numberofhhds,
		chall_timely,
		device_othercapture,
		device_timely,
		catchment_discrepancy,
		household_discrepancy,
		individual_discrepancy,
		register_quality,
		register_correct,
		experience_challenges,
		experience_maintain,
		age5,
		house_diff,
		house_diff_pct,
		indiv_diff,
		indiv_diff_pct,
		catchment_diff,
		catchment_diff_pct,
		records_complete_num
																
FROM liberia.mlw_ichis_has_supervision
GROUP BY day, month, year, district, facility, first_name, last_name, age, sex, phone, position, catchment_name, catchment_pop,	trained, device_condition, chall_connect, chall_power, device_ichis, device_otherapp, when_record, version,	device_update, ichis_household,	chr_household, ichis_individual, chr_individual, records_complete, age_match, sex_match, action_plan, numberofhhds,	chall_timely, device_othercapture, device_timely, catchment_discrepancy, household_discrepancy, individual_discrepancy,	register_quality, register_correct, experience_challenges, experience_maintain,	age5, house_diff, house_diff_pct, indiv_diff, indiv_diff_pct, catchment_diff, catchment_diff_pct, records_complete_num

ORDER BY day, month, year, district, facility, first_name, last_name, age, sex, phone, position, catchment_name, catchment_pop,	trained, device_condition, chall_connect, chall_power, device_ichis, device_otherapp, when_record, version,	device_update, ichis_household,	chr_household, ichis_individual, chr_individual, records_complete, age_match, sex_match, action_plan, numberofhhds,	chall_timely, device_othercapture, device_timely, catchment_discrepancy, household_discrepancy, individual_discrepancy,	register_quality, register_correct, experience_challenges, experience_maintain,	age5, house_diff, house_diff_pct, indiv_diff, indiv_diff_pct, catchment_diff, catchment_diff_pct, records_complete_num