select	day(start_date)     AS day,
		month(start_date)   AS month,
		year(start_date)    AS year,
		start_date date,
		end_date,
		deviceid,
		Testtype,
		Participant_ID_Number,
		Name_of_participant,
		Training_ID_Number,
		District_Health_Zone,
		District,
		Reporting_health_facility_name,
		Position,
		Qualification,
		Age_category,
		Reporting_Catchment_Area_Name,
		Catchment_area_population_size,
		Years_worked_as_a_health_worker,
		Gender,
		Q1_Score,
		Q3_score,
		Q4_Score,
		Q5_Score,
		Q6_Score,
		Q8_Score,
		Q10_Score,
		Q7_Score,
		Q8_Score2,
		Q9_score,
		Q10_Score3,
		score,
		Final_score,
		Status
from malawi.mlw_ichis_expansion
--where (year(start_date) >= '2015' and year(start_date) <= '2022')
group by start_date, year(start_date), month(start_date), day(start_date), end_date, deviceid, Testtype, Participant_ID_Number, Name_of_participant, Training_ID_Number, District_Health_Zone, District, Reporting_health_facility_name, Position, Qualification, Age_category, Reporting_Catchment_Area_Name, Catchment_area_population_size, Years_worked_as_a_health_worker, Gender, Q1_Score, Q3_score, Q4_Score, Q5_Score, Q6_Score, Q8_Score, Q10_Score, Q7_Score, Q8_Score2, Q9_score, Q10_Score3, score, Final_score, Status

order by start_date, year(start_date) desc, month(start_date), day(start_date), end_date, deviceid, Testtype, Participant_ID_Number, Name_of_participant, Training_ID_Number, District_Health_Zone, District, Reporting_health_facility_name, Position, Qualification, Age_category, Reporting_Catchment_Area_Name, Catchment_area_population_size, Years_worked_as_a_health_worker, Gender, Q1_Score, Q3_score, Q4_Score, Q5_Score, Q6_Score, Q8_Score, Q10_Score, Q7_Score, Q8_Score2, Q9_score, Q10_Score3, score, Final_score, Status